### ISSUE TITLE
How to send ECO sms (sms without sender name)

### ISSUE THREAD

**Issue by muras** [infobip/oneapi-java#5]
Hi,

As in subject.
Is it possible to send SMS without sender name (this type of sms are cheaper than PRO)
If yes how to do that with this API?

**Comment by anamarjanovic** [comment]
Hi,

It's possible to send SMS without sender name, but with sender address instead.

```
 String senderAddress = "123456789";
 String[] destinationAddress = new String[2];
 destinationAddress[0] = "456789132";
 destinationAddress[1] = "158156231";

 SMSRequest smsRequest = new SMSRequest(senderAddress, "Test", destinationAddress);
```

If you need to send messages without sender, it's possible using our new SMS API. You can find more info about the new API [here](http://dev.infobip.com/).
